### ISSUE TITLE
CR0 WriteProtect bit

### ISSUE THREAD

**Issue by roblabla** [roblabla42/KFS#15]
Apparently, if CR0 WP bit is not set, then the kernel can write in RO pages. We might want to set it.

**Comment by Orycterope** [comment]
Already done by the bootstrap when it enables paging. https://github.com/roblabla42/KFS/blob/9bd1ffcd336ae9aac7069a94f0e45c39073de4ef/bootstrap/src/paging/mod.rs#L46

I can't believe I was smart enough to think about it ... and then forget it. 

Anyway, I tried writing to a read-only page from the kernel, to test it, and it page-faulted as expected.
