### ISSUE TITLE
Unmap should free empty tables

### ISSUE THREAD

**Issue by roblabla** [roblabla42/KFS#9]
let's avoid leaking memory, shall we?

**Comment by Orycterope** [comment]
Tables are no longer leaked.
Unmap leaves empty tables, but they will be freed when the process is killed. 

I don't think it is a good idea to chek if a table is empty after every unmap we do, as it is a lot of overhead, for only gaining a frame very rarely, assuming the process won't remap something to it rigth after. So for now i'm sticking to this behaviour.
